language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.8-dev"
    - "nightly"
jobs:
  include:
    - addons:
        mariadb: 10.5
install:
    - pip install -r requirements.txt
    - sudo mysql -e "SET Password=PASSWORD('travis')"
    - sudo mysql -u travis -ptravis < schema.sql
script:
    - pytest example.py
