language: python
python:
    - "3.8"
    - "3.8-dev"
    - "nightly"
services:
    - mysql
before_install:
    - mysql -u root --password="" < schema.sql
install:
    - pip install -r requirements.txt
script:
    - pytest
